version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml   # CodeDeploy를 위해서 추가
    - scripts/**    # CodeDeploy를 위해서 추가
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'
