version: "3.4"

services:
  mysql:
    image: mysql:8.0.28
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: my-root-pwd
      MYSQL_USER: my-user
      MYSQL_PASSWORD: my-user-pwd
      MYSQL_DATABASE: my_db
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
