spring:
  config:
    activate:
      on-profile: local
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  datasource:
    url: "jdbc:mysql://localhost:3306/my_db"
    username: "my-user"
    password: "my-user-pwd"
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

---

spring:
  config:
    activate:
      on-profile: release
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  datasource:
    url: "jdbc:mysql://localhost:3306/my_db"
    username: "my-user"
    password: "my-user-pwd"
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
