spring:
  config:
    activate:
      on-profile: local
  thymeleaf:
    reactive:
      max-chunk-size: 8192
    cache: false
    prefix: classpath:/templates/
#  datasource:
#    url: "jdbc:mysql://localhost:3306/my_db"
#    username: "my-user"
#    password: "my-user-pwd"
#  jpa:
#    show-sql: true
#    open-in-view: false
#    hibernate:
#      use-new-id-generator-mappings: false
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  r2dbc:
    url: "r2dbc:mysql://localhost:3306/my_db"
    username: "my-user"
    password: "my-user-pwd"

---

spring:
  config:
    activate:
      on-profile: release
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
#  datasource:
#    url: "jdbc:mysql://database-mysql-mytodoapp.czzetsprii47.ap-northeast-2.rds.amazonaws.com:3306/my_db"
#    username: "my-user"
#    password: "my-user-pwd"
#  jpa:
#    show-sql: true
#    open-in-view: false
#    hibernate:
#      use-new-id-generator-mappings: false
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  r2dbc:
    url: "r2dbc:mysql://database-mysql-mytodoapp.czzetsprii47.ap-northeast-2.rds.amazonaws.com:3306/my_db"
    username: "my-user"
    password: "my-user-pwd"
