spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  datasource:
    url: "jdbc:mysql://localhost:3306/my_db"
    username: "my-user"
    password: "my-user-pwd"
  jpa:
    show-sql: true # 실행되는 SQL 출력
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
